layout_spectrum: 0.5516659282147884
typography_spectrum: 0.3872790769673884
color:
  brandStrength: 0.661108962027356
  lightness: 0.8160023915115744
  saturation: 0.5584372808225453
  rhythmicContrast: 0.6435351148247719
  brandColors:
    - '#FFFFFF'
    - '#4D6B83'
    - '#FFC269'
    - '#B1BEC8'
    - '#8FA2AF'
author:
  name: Tryggr.io
  email: jonyoung8020@gmail.com
  url: 'http://tryggr.io'
name: TRYGGR
navigation:
  - name: Test this link
    id: aebc5470-a3f1-4d8f-91cd-6619bccb1b8d
    type: content
title: Tryggr Blog
description: 'trust, faithful, true'
