typography_spectrum: 0.03426287695765495
color:
  brandStrength: 0.8328391502145678
  lightness: 0.83888557436876
  saturation: 0.2796210730448365
  rhythmicContrast: 0.7308847529347986
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.71781738800928
author:
  name: Jon Young
  email: jonyoung8020@gmail.com
  url: 'http://tryggr.io'
name: TRYGGR
navigation:
  - name: Test this link
    id: aebc5470-a3f1-4d8f-91cd-6619bccb1b8d
    type: content
title: 'trust, faithful, true'
description: 'trust, faithful, true'
